
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplyUkraine.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cours
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cours()
    {

        this.CoursToUniversities = new HashSet<CoursToUniversity>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public int FacultyId { get; set; }

    public string Degree { get; set; }

    public string Language { get; set; }

    public string Duration { get; set; }

    public string FirstYear { get; set; }

    public string NextYear { get; set; }



    public virtual Faculty Faculty { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CoursToUniversity> CoursToUniversities { get; set; }

}

}
