
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplyUkraine.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Description
{

    public int Id { get; set; }

    public string Header { get; set; }

    public string Text { get; set; }

    public int UniversityId { get; set; }



    public virtual University University { get; set; }

}

}
