
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplyUkraine.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Image
{

    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<int> AboutId { get; set; }

    public Nullable<int> UniversityId { get; set; }

    public Nullable<int> BlogId { get; set; }



    public virtual About About { get; set; }

    public virtual Blog Blog { get; set; }

    public virtual University University { get; set; }

}

}
