

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplyUkraine.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ApplyUkraineDBEntities : DbContext
{
    public ApplyUkraineDBEntities()
        : base("name=ApplyUkraineDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<About> Abouts { get; set; }

    public virtual DbSet<AdminDashboard> AdminDashboards { get; set; }

    public virtual DbSet<ApplicationForm> ApplicationForms { get; set; }

    public virtual DbSet<Blog> Blogs { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Cours> Courses { get; set; }

    public virtual DbSet<CoursToUniversity> CoursToUniversities { get; set; }

    public virtual DbSet<Degree> Degrees { get; set; }

    public virtual DbSet<Description> Descriptions { get; set; }

    public virtual DbSet<Faculty> Faculties { get; set; }

    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<InvitationLetter> InvitationLetters { get; set; }

    public virtual DbSet<SectionName> SectionNames { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<University> Universities { get; set; }

    public virtual DbSet<UsersForm> UsersForms { get; set; }

    public virtual DbSet<Letter> Letters { get; set; }

    public virtual DbSet<User> Users { get; set; }

}

}

