
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplyUkraine.Models
{

using System;
    using System.Collections.Generic;
    
public partial class University
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public University()
    {

        this.CoursToUniversities = new HashSet<CoursToUniversity>();

        this.Descriptions = new HashSet<Description>();

        this.Images = new HashSet<Image>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Logo { get; set; }

    public Nullable<int> Raiting { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CoursToUniversity> CoursToUniversities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Description> Descriptions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Image> Images { get; set; }

}

}
